/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package newpackageFORUI;
import model.BookingData;
import java.time.YearMonth;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException; 
import javax.swing.JOptionPane;
/**
 *
 * @author Lenovo
 */
public class PaymentPanelCard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PaymentPanelCard.class.getName());
    private final BookingData bookingData; // <-- ADDED FIELD
    /**
     * Creates new form PaymentPanelCard
     */
    public PaymentPanelCard() {
        initComponents();
        setLocationRelativeTo(null);   
        this.bookingData = null; // Set null for design mode
    }
    
    public PaymentPanelCard(BookingData bookingData) { // <-- ADDED CONSTRUCTOR
        this.bookingData = bookingData;
        initComponents();
        setLocationRelativeTo(null);   
        
        double grandTotal = bookingData.getGrandTotal();
        jTotalAmount.setText(String.format("Php %,.2f", grandTotal));
        
        // 2. Make the Total amount due field read-only
        jTotalAmount.setEditable(false);
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jCardNum = new javax.swing.JTextField();
        jExpiryDate = new javax.swing.JTextField();
        jCVV = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTotalAmount = new javax.swing.JTextField();
        jBackButton = new javax.swing.JButton();
        jConfirm = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CREDIT PAYMENT");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Card Number:");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("CVV:");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Expiry Date:");

        jLabel5.setText("TOTAL AMOUNT DUE:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jCardNum, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                    .addComponent(jExpiryDate)
                    .addComponent(jCVV))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jTotalAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCardNum, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jTotalAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jExpiryDate, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(jCVV, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        jBackButton.setText("BACK");
        jBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBackButtonActionPerformed(evt);
            }
        });

        jConfirm.setText("CONFIRM");
        jConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jConfirmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(251, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 156, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBackButtonActionPerformed
        // TODO add your handling code here:
       PaymentPanelMainMenu paymentMenu = new PaymentPanelMainMenu(bookingData);
       paymentMenu.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jBackButtonActionPerformed

    private void jConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jConfirmActionPerformed
        // TODO add your handling code here:
        String cardNumber = jCardNum.getText().trim();
            String expiryDate = jExpiryDate.getText().trim();
            String cvv = jCVV.getText().trim();

            // --- 1. Card Number Validation (13-19 digits, numeric) ---
            // Common card numbers are 13 to 19 digits long.
            if (!cardNumber.matches("^\\d{16}$")) {
                JOptionPane.showMessageDialog(this, 
                    "Invalid Card Number. Must be 16 digits.", 
                    "Validation Error", JOptionPane.ERROR_MESSAGE);
                jCardNum.requestFocus();
                return;
            }

            // --- 2. Expiry Date Validation (MM/YY or MM/YYYY, and future date) ---
            YearMonth expDate;
            try {
                DateTimeFormatter formatter;
                // Determine format based on length
                if (expiryDate.length() == 5 && expiryDate.contains("/")) { // MM/YY
                    formatter = DateTimeFormatter.ofPattern("MM/yy");
                } else if (expiryDate.length() == 7 && expiryDate.contains("/")) { // MM/YYYY
                     formatter = DateTimeFormatter.ofPattern("MM/yyyy");
                } else {
                    JOptionPane.showMessageDialog(this, 
                        "Invalid Expiry Date format. Use MM/YY or MM/YYYY.", 
                        "Validation Error", JOptionPane.ERROR_MESSAGE);
                    jExpiryDate.requestFocus();
                    return;
                }

                expDate = YearMonth.parse(expiryDate, formatter);
            } catch (DateTimeParseException e) {
                 JOptionPane.showMessageDialog(this, 
                    "Invalid Expiry Date format or value. Use MM/YY or MM/YYYY.", 
                    "Validation Error", JOptionPane.ERROR_MESSAGE);
                jExpiryDate.requestFocus();
                return;
            }

            // Check if the expiry date is in the future (or current month/year)
            YearMonth now = YearMonth.now();
            if (expDate.isBefore(now)) {
                JOptionPane.showMessageDialog(this, 
                    "Card has expired. Please use a valid card.", 
                    "Validation Error", JOptionPane.ERROR_MESSAGE);
                jExpiryDate.requestFocus();
                return;
            }

            // --- 3. CVV Validation (3 or 4 digits, numeric) ---
            if (!cvv.matches("^\\d{3,4}$")) {
                JOptionPane.showMessageDialog(this, 
                    "Invalid CVV. Must be 3 or 4 digits.", 
                    "Validation Error", JOptionPane.ERROR_MESSAGE);
                jCVV.requestFocus();
                return;
            }

            // --- 4. Payment Success ---
            // Get total amount for display
            String totalDueText = jTotalAmount.getText().replaceAll("[^\\d.]", "");
            double totalDue = 0.0;
            try {
                 totalDue = Double.parseDouble(totalDueText);
            } catch (NumberFormatException e) {
                 // Defensive catch
            }

            String message = String.format("Payment Successful!\n\n"
                                         + "Card Number: **** **** **** %s\n"
                                         + "Total Charged: Php %,.2f", 
                                         cardNumber.substring(cardNumber.length() - 4), totalDue);

            JOptionPane.showMessageDialog(this, message, "Credit Payment Completed", JOptionPane.INFORMATION_MESSAGE);

            // Close the window after successful payment
            this.dispose();
    }//GEN-LAST:event_jConfirmActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PaymentPanelCard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBackButton;
    private javax.swing.JTextField jCVV;
    private javax.swing.JTextField jCardNum;
    private javax.swing.JButton jConfirm;
    private javax.swing.JTextField jExpiryDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTotalAmount;
    // End of variables declaration//GEN-END:variables
}
